### PR TITLE
ID - Adding ability to modify legend/globe

### PR DESCRIPTION
**Pull request by zaydor**
I reset this branch back to master and updated the code a bit to fit with latest accepted PR.

### CODE REVIEW

**Review by dafrenchyman — CHANGES_REQUESTED** [review]
I played with this PR. When I switch datasets when I've changed the upper/lower bounds, it doesn't reset itself. That needs to be fixed or when we switch between datasets we're going to run into issues.

**Comment by dafrenchyman** [comment]
I also rebased this on master for you.

**Comment by zaydor** [comment]
I changed the logic for slider updates a bit and also got the slider to update about 2 seconds faster when selecting a new data set. The bounds not changing bug should be fixed now.

**Review by dafrenchyman — APPROVED** [review]
I did change one minor thing. It's not good to return a "failed" or "success" string. You should just return a boolean true/false. I also changed the variable name so it made more sense. Instead of "response" I changed it to "isValid".

It's minor, but it makes the code more readable (which is important).

It looks great though. I tested it out and it produces beautiful charts!

**Pull request merged**
