### PR TITLE
ID - Modified downloaded CSV files to be easier to read and understand

### PR DESCRIPTION
**Pull request by zaydor**
Changes to CSV file include:

* Added more information to header of CSV including value name and units
* removed "mrsharky" from downloaded filename
* Both Gridded and Time Series CSV have information on Level, Date, Value, Lat, and Lon

### CODE REVIEW

**Review by dafrenchyman — CHANGES_REQUESTED** [review]
Hi Isaiah,

I'm working on the CSV branch, and I've only discovered one issue. You seem to only print out the values for the repeated fields on the first row. I can sort of understand why you did that, but on the time series charts, when you save multiple dates it's a bit weird. Since we're not storing these files on our end, and it's just being generated by the user's browser, I don't think it hurts to save the values, even if we're repeating them.

If you add that in I think it should be fine.

**Review by dafrenchyman — CHANGES_REQUESTED** [review]
I can't get this branch to build. I get the following error:

`ERROR in src/app/timeseries-menu.component.ts(182,45): error TS2339: Property 'GenerateAxisTitle' does not exist on type 'Settings'.
src/app/view.component.ts(545,45): error TS2339: Property 'GenerateAxisTitle' does not exist on type 'Settings'.`

**Review by dafrenchyman — COMMENTED** [review]
Zaydor, please review the updates I did to clean up the formatting.

**Review by zaydor — COMMENTED** [review]
Looks a lot neater than the automatic linting.

**Comment by dafrenchyman** [comment]
> Looks a lot neater than the automatic linting.

It's still auto-linting it. You're just trying to put too much stuff in one line of code. Even if you're only going to use a value once, it's totally fine to make a variable out of it.

**Review by dafrenchyman — APPROVED** [review]
Approved.

**Comment by dafrenchyman** [comment]
Please rebase your code off of master.

**Review by dafrenchyman — CHANGES_REQUESTED** [review]
Please rebase off of master.

**Review by dafrenchyman — APPROVED** [review]

**Review by dafrenchyman — CHANGES_REQUESTED** [review]
Rebase off master.

**Pull request closed without merging**
