### PR TITLE
ID - More updates to the setting tab

### PR DESCRIPTION
**Pull request by zaydor**
Updated menu and tab buttons per request by Sam. Fixed a typo. Also minor changes to the graphics tab for better readability.

### CODE REVIEW

**Review by dafrenchyman — CHANGES_REQUESTED** [review]
Needs correcting before we merge:
- If the dataset font is going to be changed, I think the font should be changed everywhere. The legend (top right) wasn't changed and neither was the date/layer (lower right).
- The tabs in the menu look busy and ugly (the stuff that changed from images to text). I'm not of the opinion that they need changing. After all, we have tool-tips on them. However, if this is what you guys want, the current change doesn't look good. Maybe some padding between them, and/or drop the second word in each of them. 

Just an idea, this isn't holding up the PR:
- The yellow "+" that turned into a yellow "menu" looks pretty bad. What if we changed it to a "hamburger" icon instead?. Also, what if we moved the menu selection out of the map screen and instead up on top on the title bar (to the left).
- The new font goes under the new yellow "menu" icon when the text gets long. This issue has probably been here since the beginning.

**Comment by zaydor** [comment]
I reverted the changes to the tabs. I was not much of a fan of the change either but Sam said it might help with understanding what each tab means/includes. But since there is tooltips then I agree with you that it should be fine. I also reverted the font color back to the original. But I did add an exit button for the sidenav and changed the menu button to the more sleek hamburger icon. I think it looks a lot better. What do you think?

**Comment by dafrenchyman** [comment]
I'll review tonight when I get back from work.

**Review by dafrenchyman — APPROVED** [review]
I'm accepting the changes (I'll merge in the changes for you too) so I can deploy it tonight).

I like the hamburger and the close X. I feel like the hamburger will be hard to see if it's not inside of something with color.

I'm actually wondering if it would look nice up above next to the title ("4DVD .... ").

Anyway, overall I think it does look cleaner so great job.

**Pull request merged**
